import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { AppLayout } from '../components/AppLayout';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
    return (
        <AppLayout>
            <div className={styles.container}>
                <Head>
                    <title>Create Next App</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <footer className={styles.footer}></footer>
            </div>
        </AppLayout>
    );
};

export default Home;
